language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
cache:
  directories:
    - node_modules
script:
  - yarn docs:build # npm run docs:build
deploy:
  committer_from_gh: true
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  target_branch: master
  keep_history: true
  on:
    branch: master
